### PR TITLE
Grammar edits chap3

### PR DESCRIPTION
**Pull request by crclark96**
started changing source unicode characters to latex commands for portability

some of the sentences may need more refactoring but I'll get to those later

### CODE REVIEW

**Comment by leviathanch** [comment]
Thanks a lot for the contribution! :+1:
Would be awesome if you knew some folks who know about chip manufacturing, that they could have a look at it as well

**Comment by crclark96** [comment]
I've mailed the groups I think would be interested in being involved

I'll re-up with them to see if they have any ideas or contacts I can talk to

**Comment by leviathanch** [comment]
Awesome! Thanks so much!

**Comment by crclark96** [comment]
we have a VLSI design team, but we don't have any nanotech people here unfortunately :/

i'll see if we have any contacts at other universities doing similar projects. no promises though

**Pull request merged**
